ALTER TABLE `dates` DROP `id`;
ALTER TABLE `dates` AUTO_INCREMENT = 1;
ALTER TABLE `dates` ADD `id` int UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST;

ALTER TABLE `news` DROP `id`;
ALTER TABLE `news` AUTO_INCREMENT = 1;
ALTER TABLE `news` ADD `id` int UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST;

ALTER TABLE `settings` DROP `id`;
ALTER TABLE `settings` AUTO_INCREMENT = 1;
ALTER TABLE `settings` ADD `id` int UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST;

ALTER TABLE `users` DROP `id`;
ALTER TABLE `users` AUTO_INCREMENT = 1;
ALTER TABLE `users` ADD `id` int UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST;